version: "3"

tasks:
  build:
    env:
      APP_NAME: hound
      APP_PUBLISHER: StorkKershaw
      APP_URL: https://github.com/StorkKershaw/hound
      GOOS: windows
      GOARCH: amd64
      OUTPUT_DIR: .\
    cmds:
      - go mod tidy
      - go-winres make --product-version=$APP_VERSION --file-version=$APP_VERSION
      - go build -ldflags='-H=windowsgui'
      - ISCC.exe /Qp /DAppName=$APP_NAME /DAppVersion=$APP_VERSION /DAppPublisher=$APP_PUBLISHER /DAppURL=$APP_URL /DOutputDir=$OUTPUT_DIR installer.iss
