// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package connectivity

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureConnectionProfile string = "rc(Windows.Networking.Connectivity.ConnectionProfile;{71ba143c-598e-49d0-84eb-8febaedcc195})"

type ConnectionProfile struct {
	ole.IUnknown
}

func (impl *ConnectionProfile) GetNetworkConnectivityLevel() (NetworkConnectivityLevel, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiConnectionProfile))
	defer itf.Release()
	v := (*iConnectionProfile)(unsafe.Pointer(itf))
	return v.GetNetworkConnectivityLevel()
}

const GUIDiConnectionProfile string = "71ba143c-598e-49d0-84eb-8febaedcc195"
const SignatureiConnectionProfile string = "{71ba143c-598e-49d0-84eb-8febaedcc195}"

type iConnectionProfile struct {
	ole.IInspectable
}

type iConnectionProfileVtbl struct {
	ole.IInspectableVtbl

	GetProfileName                uintptr
	GetNetworkConnectivityLevel   uintptr
	GetNetworkNames               uintptr
	GetConnectionCost             uintptr
	GetDataPlanStatus             uintptr
	GetNetworkAdapter             uintptr
	GetLocalUsage                 uintptr
	GetLocalUsagePerRoamingStates uintptr
	GetNetworkSecuritySettings    uintptr
}

func (v *iConnectionProfile) VTable() *iConnectionProfileVtbl {
	return (*iConnectionProfileVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iConnectionProfile) GetNetworkConnectivityLevel() (NetworkConnectivityLevel, error) {
	var out NetworkConnectivityLevel
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNetworkConnectivityLevel,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out NetworkConnectivityLevel
	)

	if hr != 0 {
		return NetworkConnectivityLevelNone, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiConnectionProfile2 string = "e2045145-4c9f-400c-9150-7ec7d6e2888a"
const SignatureiConnectionProfile2 string = "{e2045145-4c9f-400c-9150-7ec7d6e2888a}"

type iConnectionProfile2 struct {
	ole.IInspectable
}

type iConnectionProfile2Vtbl struct {
	ole.IInspectableVtbl

	GetIsWwanConnectionProfile      uintptr
	GetIsWlanConnectionProfile      uintptr
	GetWwanConnectionProfileDetails uintptr
	GetWlanConnectionProfileDetails uintptr
	GetServiceProviderGuid          uintptr
	GetSignalBars                   uintptr
	GetDomainConnectivityLevel      uintptr
	GetNetworkUsageAsync            uintptr
	GetConnectivityIntervalsAsync   uintptr
}

func (v *iConnectionProfile2) VTable() *iConnectionProfile2Vtbl {
	return (*iConnectionProfile2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiConnectionProfile3 string = "578c2528-4cd9-4161-8045-201cfd5b115c"
const SignatureiConnectionProfile3 string = "{578c2528-4cd9-4161-8045-201cfd5b115c}"

type iConnectionProfile3 struct {
	ole.IInspectable
}

type iConnectionProfile3Vtbl struct {
	ole.IInspectableVtbl

	GetAttributedNetworkUsageAsync uintptr
}

func (v *iConnectionProfile3) VTable() *iConnectionProfile3Vtbl {
	return (*iConnectionProfile3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiConnectionProfile4 string = "7a2d42cd-81e0-4ae6-abed-ab9ca13eb714"
const SignatureiConnectionProfile4 string = "{7a2d42cd-81e0-4ae6-abed-ab9ca13eb714}"

type iConnectionProfile4 struct {
	ole.IInspectable
}

type iConnectionProfile4Vtbl struct {
	ole.IInspectableVtbl

	GetProviderNetworkUsageAsync uintptr
}

func (v *iConnectionProfile4) VTable() *iConnectionProfile4Vtbl {
	return (*iConnectionProfile4Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiConnectionProfile5 string = "85361ec7-9c73-4be0-8f14-578eec71ee0e"
const SignatureiConnectionProfile5 string = "{85361ec7-9c73-4be0-8f14-578eec71ee0e}"

type iConnectionProfile5 struct {
	ole.IInspectable
}

type iConnectionProfile5Vtbl struct {
	ole.IInspectableVtbl

	GetCanDelete   uintptr
	TryDeleteAsync uintptr
}

func (v *iConnectionProfile5) VTable() *iConnectionProfile5Vtbl {
	return (*iConnectionProfile5Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiConnectionProfile6 string = "dc27dfe2-7a6f-5d0e-9589-2fe2e5b6f9aa"
const SignatureiConnectionProfile6 string = "{dc27dfe2-7a6f-5d0e-9589-2fe2e5b6f9aa}"

type iConnectionProfile6 struct {
	ole.IInspectable
}

type iConnectionProfile6Vtbl struct {
	ole.IInspectableVtbl

	IsDomainAuthenticatedBy uintptr
}

func (v *iConnectionProfile6) VTable() *iConnectionProfile6Vtbl {
	return (*iConnectionProfile6Vtbl)(unsafe.Pointer(v.RawVTable))
}
