// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package connectivity

type NetworkConnectivityLevel int32

const SignatureNetworkConnectivityLevel string = "enum(Windows.Networking.Connectivity.NetworkConnectivityLevel;i4)"

const (
	NetworkConnectivityLevelNone                      NetworkConnectivityLevel = 0
	NetworkConnectivityLevelLocalAccess               NetworkConnectivityLevel = 1
	NetworkConnectivityLevelConstrainedInternetAccess NetworkConnectivityLevel = 2
	NetworkConnectivityLevelInternetAccess            NetworkConnectivityLevel = 3
)
