// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package connectivity

import (
	"sync"
	"time"
	"unsafe"

	"github.com/StorkKershaw/hound/internal/windows/delegate"
	"github.com/StorkKershaw/hound/internal/windows/kernel32"
	"github.com/go-ole/go-ole"
)

const GUIDNetworkStatusChangedEventHandler string = "71ba143f-598e-49d0-84eb-8febaedcc195"
const SignatureNetworkStatusChangedEventHandler string = "delegate({71ba143f-598e-49d0-84eb-8febaedcc195})"

type NetworkStatusChangedEventHandler struct {
	ole.IUnknown
	sync.Mutex
	refs uintptr
	IID  ole.GUID
}

type NetworkStatusChangedEventHandlerVtbl struct {
	ole.IUnknownVtbl
	Invoke uintptr
}

type NetworkStatusChangedEventHandlerCallback func(instance *NetworkStatusChangedEventHandler, sender unsafe.Pointer)

var callbacksNetworkStatusChangedEventHandler = &networkStatusChangedEventHandlerCallbacks{
	mu:        &sync.Mutex{},
	callbacks: make(map[unsafe.Pointer]NetworkStatusChangedEventHandlerCallback),
}

var releaseChannelsNetworkStatusChangedEventHandler = &networkStatusChangedEventHandlerReleaseChannels{
	mu:    &sync.Mutex{},
	chans: make(map[unsafe.Pointer]chan struct{}),
}

func NewNetworkStatusChangedEventHandler(iid *ole.GUID, callback NetworkStatusChangedEventHandlerCallback) *NetworkStatusChangedEventHandler {
	// create type instance
	size := unsafe.Sizeof(*(*NetworkStatusChangedEventHandler)(nil))
	instPtr := kernel32.Malloc(size)
	inst := (*NetworkStatusChangedEventHandler)(instPtr)

	// get the callbacks for the VTable
	callbacks := delegate.RegisterCallbacks(instPtr, inst)

	// the VTable should also be allocated in the heap
	sizeVTable := unsafe.Sizeof(*(*NetworkStatusChangedEventHandlerVtbl)(nil))
	vTablePtr := kernel32.Malloc(sizeVTable)

	inst.RawVTable = (*interface{})(vTablePtr)

	vTable := (*NetworkStatusChangedEventHandlerVtbl)(vTablePtr)
	vTable.IUnknownVtbl = ole.IUnknownVtbl{
		QueryInterface: callbacks.QueryInterface,
		AddRef:         callbacks.AddRef,
		Release:        callbacks.Release,
	}
	vTable.Invoke = callbacks.Invoke

	// Initialize all properties: the malloc may contain garbage
	inst.IID = *iid // copy contents
	inst.Mutex = sync.Mutex{}
	inst.refs = 0

	callbacksNetworkStatusChangedEventHandler.add(unsafe.Pointer(inst), callback)

	// See the docs in the releaseChannelsNetworkStatusChangedEventHandler struct
	releaseChannelsNetworkStatusChangedEventHandler.acquire(unsafe.Pointer(inst))

	inst.addRef()
	return inst
}

func (r *NetworkStatusChangedEventHandler) GetIID() *ole.GUID {
	return &r.IID
}

// addRef increments the reference counter by one
func (r *NetworkStatusChangedEventHandler) addRef() uintptr {
	r.Lock()
	defer r.Unlock()
	r.refs++
	return r.refs
}

// removeRef decrements the reference counter by one. If it was already zero, it will just return zero.
func (r *NetworkStatusChangedEventHandler) removeRef() uintptr {
	r.Lock()
	defer r.Unlock()

	if r.refs > 0 {
		r.refs--
	}

	return r.refs
}

func (instance *NetworkStatusChangedEventHandler) Invoke(instancePtr, rawArgs0, rawArgs1, rawArgs2, rawArgs3, rawArgs4, rawArgs5, rawArgs6, rawArgs7, rawArgs8 unsafe.Pointer) uintptr {
	senderPtr := rawArgs0

	// See the quote above.
	sender := (unsafe.Pointer)(senderPtr)
	if callback, ok := callbacksNetworkStatusChangedEventHandler.get(instancePtr); ok {
		callback(instance, sender)
	}
	return ole.S_OK
}

func (instance *NetworkStatusChangedEventHandler) AddRef() uintptr {
	return instance.addRef()
}

func (instance *NetworkStatusChangedEventHandler) Release() uintptr {
	rem := instance.removeRef()
	if rem == 0 {
		// We're done.
		instancePtr := unsafe.Pointer(instance)
		callbacksNetworkStatusChangedEventHandler.delete(instancePtr)

		// stop release channels used to avoid
		// https://github.com/golang/go/issues/55015
		releaseChannelsNetworkStatusChangedEventHandler.release(instancePtr)

		kernel32.Free(unsafe.Pointer(instance.RawVTable))
		kernel32.Free(instancePtr)
	}
	return rem
}

type networkStatusChangedEventHandlerCallbacks struct {
	mu        *sync.Mutex
	callbacks map[unsafe.Pointer]NetworkStatusChangedEventHandlerCallback
}

func (m *networkStatusChangedEventHandlerCallbacks) add(p unsafe.Pointer, v NetworkStatusChangedEventHandlerCallback) {
	m.mu.Lock()
	defer m.mu.Unlock()

	m.callbacks[p] = v
}

func (m *networkStatusChangedEventHandlerCallbacks) get(p unsafe.Pointer) (NetworkStatusChangedEventHandlerCallback, bool) {
	m.mu.Lock()
	defer m.mu.Unlock()

	v, ok := m.callbacks[p]
	return v, ok
}

func (m *networkStatusChangedEventHandlerCallbacks) delete(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	delete(m.callbacks, p)
}

// typedEventHandlerReleaseChannels keeps a map with channels
// used to keep a goroutine alive during the lifecycle of this object.
// This is required to avoid causing a deadlock error.
// See this: https://github.com/golang/go/issues/55015
type networkStatusChangedEventHandlerReleaseChannels struct {
	mu    *sync.Mutex
	chans map[unsafe.Pointer]chan struct{}
}

func (m *networkStatusChangedEventHandlerReleaseChannels) acquire(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	c := make(chan struct{})
	m.chans[p] = c

	go func() {
		// we need a timer to trick the go runtime into
		// thinking there's still something going on here
		// but we are only really interested in <-c
		t := time.NewTimer(time.Minute)
		for {
			select {
			case <-t.C:
				t.Reset(time.Minute)
			case <-c:
				t.Stop()
				return
			}
		}
	}()
}

func (m *networkStatusChangedEventHandlerReleaseChannels) release(p unsafe.Pointer) {
	m.mu.Lock()
	defer m.mu.Unlock()

	if c, ok := m.chans[p]; ok {
		close(c)
		delete(m.chans, p)
	}
}
