name: Build Installer for Windows and Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Dependencies
        run: |
          go install github.com/go-task/task/v3/cmd/task@latest
          go install github.com/tc-hib/go-winres@latest
          winget install --accept-package-agreements --accept-source-agreements --disable-interactivity --id JRSoftware.InnoSetup --exact --source winget
          Write-Output -InputObject "${env:LOCALAPPDATA}\Programs\Inno Setup 6" | Out-File -FilePath "$env:GITHUB_PATH" -Encoding utf8 -Append

      - name: Build Installer
        env:
          APP_VERSION: ${{ github.ref_name }}
        run: task build

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: "**/hound v${{ github.ref_name }}.exe"
